-- Create the table for rain gauge records
create table public.registros (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha date not null,
  litros double precision not null
);

-- Enable Row Level Security (RLS) - Optional for this simple app, but good practice
-- alter table public.registros enable row level security;

-- Create a policy that allows anyone to read/write for now since we are handling auth efficiently in the app
-- For a real app, you'd want authenticated users only.
-- create policy "Enable read access for all users" on public.registros for select using (true);
-- create policy "Enable insert access for all users" on public.registros for insert with check (true);
-- create policy "Enable delete access for all users" on public.registros for delete using (true);
